sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version

script:
  - bash test.sh
  - bash chap4/code/world.sh
  #- bash chap4/code/image.sh -h
  #- bash chap4/code/image.sh -q chap4/images 80
  #- bash chap4/code/image.sh -c chap4/images
  #- bash chap4/code/image.sh -w chap4/images cuccs
  #- bash chap4/code/image.sh -r chap4/images pre
  #- bash chap4/code/image.sh -j chap4/images

after_script:
  - /usr/bin/shellcheck test.sh
  #- /usr/bin/shellcheck chap4/code/image.sh
  - /usr/bin/shellcheck chap4/code/world.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
